require 'json'

platform :ios, '15.0'
install! 'cocoapods', :warn_missing_podspec_sources => false

def capacitor_pods
  # Capacitor core
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios/node_modules/@capacitor/cordova-ios'
end

target 'App' do
  capacitor_pods

  # Capacitor plugins (تُحدَّث تلقائيًا عند تشغيل `npx cap sync ios` على جهازك)
  pod 'CapacitorApp', :path => '../node_modules/@capacitor/app'
  pod 'CapacitorGeolocation', :path => '../node_modules/@capacitor/geolocation'
  pod 'CapacitorSplashScreen', :path => '../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../node_modules/@capacitor/status-bar'

  use_frameworks!
end

post_install do |installer|
  assertDeploymentTarget(installer)
end

def assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if deployment_target.to_f < 15.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
